uicontrol(gcf,...
   'Style','frame',...
    'Position',[145,283,306,71],...
    'BackgroundColor','r');

uicontrol(gcf,...
    'Style','text',...
    'Position',[148,322,300,30],...
    'BackgroundColor',[1.0 1.0 1.0],...
    'String','VOLTAGE STABILITY TOOLBOX',...
    'FontSize',12);
      
uicontrol(gcf,...
    'Style','text',...
    'Position',[148,305,300,20],...
    'BackgroundColor',[1.0 1.0 1.0],...
    'String','Center for Electric Power Engineering',...
    'Fontsize',12);

uicontrol(gcf,... 
    'Style','text',...
    'Position',[148,285,300,22],...
    'BackgroundColor',[1.0 1.0 1.0],...
    'String','Drexel University',...
    'FontSize',12);
