% This M-file adds a title to the current simulation window:
%For example:Cuurent System:IEEE3b

tmp_fig=gcf;

    uicontrol(tmp_fig,...
        'Style','frame',...
        'Position',[150,368,216,28],...
        'BackgroundColor','r');

    SystemName=uicontrol(tmp_fig,...
        'Style','text',...
        'BackgroundColor',[0.8 0.8 0.8],...
        'Position',[153,371,210,22],...
        'HorizontalAlignment','Center',...
        'String',['Current System: ',CurrentSystem]);
