    tmp_fig=gcf;

    uicontrol(tmp_fig,...
        'Style','frame',...
        'BackgroundColor','b',...
        'Position',[25,200,5*90+10,113]);  % EDITED BY: Vedanshu

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,205,95,18],...
        'HorizontalAlignment','Left',...
        'String','MaxIterations');
    MaxIterationControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,205,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(20),...
        'Callback','lfcntrup1');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,205,90,18],...
        'HorizontalAlignment','left',...
        'String','Reporting');
    ReportControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[290,205,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(5),...
        'Callback','lfcntrup1');

    % **************************************
    %    Start & Stop Buttons
    %***************************************
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','R',...
        'Position',[370,204,45,28],...
        'HorizontalAlignment','Center',...
        'String','Save',...
        'Callback','savedata');
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','R',...
        'Position',[420,204,60,28],...
        'HorizontalAlignment','Center',...
        'String','Save As',...
        'Callback','savasdat');

    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor',[.1 1 .1],...
        'Position',[370,235,45,28],...
        'HorizontalAlignment','Center',...
        'String','Start',...
        'Callback','eval(LF_Alg)');
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','R',...
        'Position',[420,235,60,28],...
        'HorizontalAlignment','Center',...
        'String','Reset',...
        'Callback','lfreset');
         
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,225,95,18],...
        'HorizontalAlignment','Left',...
        'String','Error');
    AbsErrorDisp=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[126,225,74,18],...
        'HorizontalAlignment','Center',...
        'String','NA');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,225,90,18],...
        'HorizontalAlignment','Left',...
        'String','RelError');
    RelErrorDisp=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[291,225,74,18],...
        'HorizontalAlignment','Center',...
        'String','NA');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,245,95,18],...
        'HorizontalAlignment','Left',...
        'String','Tolerence');
    AbsTolControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,245,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(LFAbsTol,5),...
        'Callback','lfcntrup1');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,245,90,18],...
        'HorizontalAlignment','Left',...
        'String','RelTolerence');
    RelTolControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[290,245,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(LFRelTol,5),...
        'Callback','lfcntrup1');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,290,223,18],...
        'HorizontalAlignment','Center',...
        'String','Algorithm');

    %******************************
    % Iterations box
    %******************************
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[258,290,111,18],...
        'HorizontalAlignment','Center',...
        'String','Iterations');
    NumIterations=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[370,290,108,18],...
        'BackgroundColor','y',...
        'HorizontalAlignment','Right',...
        'String','0');

    %******************************
    % Elapsed Time box
    %******************************
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[258,270,111,18],...
        'HorizontalAlignment','Center',...
        'String','Time/Iteration');
    IterationTime=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[370,270,108,18],...
        'BackgroundColor','y',...
        'HorizontalAlignment','Right',...
        'String','0');
