    tmp_fig=gcf;

    uicontrol(tmp_fig,...
        'Style','frame',...
        'BackgroundColor','b',...
        'Position',[25,200,5*90+10,150]);  % EDITED BY: Vedanshu

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,245,95,18],...
        'HorizontalAlignment','Left',...
        'String','MaxIterations',...
        'BackgroundColor',[0.7 0.7 0.7]);
     
    MaxIterationControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,245,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(20),...
        'Callback','lfcntrup');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,245,90,18],...
        'HorizontalAlignment','Left',...
        'String','Reporting');
    ReportControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[290,245,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(5),...
        'Callback','lfcntrup');

    % **************************************
    %    Start & Stop Buttons
    %***************************************
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','r',...
        'Position',[370,244,45,28],...
        'HorizontalAlignment','Center',...
        'String','Save');
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor',[1 0 0],...
        'Position',[420,244,60,28],...
        'HorizontalAlignment','Center',...
        'String','Save As');

    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','g',...
        'Position',[370,275,45,28],...
        'HorizontalAlignment','Center',...
        'String','Start',...
        'Callback','eval(LF_Alg)');
    uicontrol(tmp_fig,...
        'Style','pushbutton',...
        'BackgroundColor','r',...
        'Position',[420,275,60,28],...
        'HorizontalAlignment','Center',...
        'String','Reset',...
        'Callback','lfreset');
         
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,265,95,18],...
        'HorizontalAlignment','Left',...
        'String','Error');
    AbsErrorDisp=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[126,265,74,18],...
        'HorizontalAlignment','Center',...
        'String','NA');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,265,90,18],...
        'HorizontalAlignment','left',...
        'String','RelError');
    RelErrorDisp=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[291,265,74,18],...
        'HorizontalAlignment','Center',...
        'String','NA');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,285,95,18],...
        'HorizontalAlignment','Left',...
        'String','Tolerence');
    AbsTolControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,285,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(LFAbsTol,5),...
        'Callback','lfcntrup');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[200,285,90,18],...
        'HorizontalAlignment','Left',...
        'String','RelTolerence');
    RelTolControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[290,285,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(LFRelTol,5),...
        'Callback','lfcntrup');

    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,330,223,18],...
        'HorizontalAlignment','Center',...
        'String','Algorithm');

    %******************************
    % Iterations box
    %******************************
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[258,330,111,18],...
        'HorizontalAlignment','Center',...
        'String','Iterations');
    NumIterations=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[370,330,108,18],...
        'BackgroundColor','y',...
        'HorizontalAlignment','Right',...
        'String','0');
     
    %******************************
    % NR and NRS Step size box
    %******************************
    
    	 uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,225,95,18],...
        'HorizontalAlignment','Left',...
        'String','NR_steps');
    NR_stepControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,225,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(NR_steps,5),...
        'Callback','lfcntrup1');
        
         uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[30,205,95,18],...
        'HorizontalAlignment','Left',...
        'String','NRS_Steps');
    NRS_stepControl=uicontrol(tmp_fig,...
        'Style','edit',...
        'Position',[125,205,75,18],...
        'HorizontalAlignment','Right',...
        'String',num2str(NRS_Steps,5),...
        'Callback','lfcntrup1');
    %******************************
    % Elapsed Time box
    %******************************
    uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[258,310,111,18],...
        'HorizontalAlignment','Center',...
        'String','Time/Iteration');
    IterationTime=uicontrol(tmp_fig,...
        'Style','text',...
        'Position',[370,310,108,18],...
        'BackgroundColor','y',...
        'HorizontalAlignment','Right',...
        'String','0');
